### ISSUE TITLE
Application crash when connection becomes unstable

### ISSUE THREAD

**Issue by benjaminwanders** [Dragennd/NetworkAnalyzer#2]
Hi,

I use NetworkAnalyzer to monitor my own internet connection, our ISP has been having issues for over 4 months and I need to send logging/evidence of outages. Scenario:

- Latency Monitor
- I use 5 hosts: 1.1.1.1 / 8.8.8.8 / 208.67.220.220 (DNS Servers) and google.com and tweakers.net
- When package loss hits around 30% across all hosts (monitored through a little powershell script with those 5 same hosts) NetworkAnalyzer crashes and I can't generate a report for that session.

The way the reports are generated by NA are brilliant and are very good evidence in my fight with the ISP. Can replicate every time.

**Comment by Dragennd** [comment]
Hmm, interesting that it crashes then. I'm currently working on implementing local session data storage so even when a crash occurs you won't lose any data logged up until that point. This will help alleviate the issues of losing data. I'll look into why it would crash at that point though and work on a fix to have out with the next build.

**Comment by benjaminwanders** [comment]
In case it matters, Windows 11 23H2, tried on 24H2 as well and it's the same. Just a LAN connection. If you find it hard to replicate, can help and do some testing. 

<sub>Sidenote: Happy to see feedback so fast and taken seriously :)</sub>

**Comment by Dragennd** [comment]
Always good to have feedback on things and be made aware of problems. My intention is to write a piece of software that is stable and usable so I welcome any user input.

As I'm still learning C#, I can't promise I'll have an immediate fix for some issues (though this one I have an idea of where the problem is), but I'll do my best to fix any actual bugs brought up.

**Comment by Dragennd** [comment]
@benjaminwanders I believe the issue here is probably that I was not properly disposing of the Ping class when each instance was finished. I've since added logic to dispose of each Ping instance upon completion which should resolve this issue.

Just in case there are other contributing factors here, I've also added logging which should help with further troubleshooting this issue.

Update: [Version 1.6.0 is available today!](https://github.com/Dragennd/NetworkAnalyzer/releases/tag/1.6.0)
